[workspace]

[package]
name = "iota-wallet-swift-binding"
version = "0.1.0"
authors = ["Thoralf Müller <thoralf.mueller@iota.org"]
edition = "2018"

[lib]
name = "wallet"
crate-type = ["cdylib", "staticlib"]

[dependencies]
tokio = { version = "1.11", features = ["full"] }
once_cell = "1.5.0"
iota-wallet = { git = "https://github.com/iotaledger/wallet.rs", rev = "5b2da7f8f5e4d20e7412bc62772fce8e9f744290", default-features = false, features = ["stronghold", "ledger-nano", "ledger-nano-simulator"] }
serde_json = "1.0"
riker = "0.4"
serde = "1.0"
bee-common = "0.4.1"
log = "0.4"
futures = "0.3"